### PR TITLE
How to Link it to My Server

### PR DESCRIPTION
**Pull request by filestoreinnet**
I want to use link this skill to my server, for example i have a server with all functions of youtube api and youtube_dl and i want link it with this skill,
This function will avoid error( this script  had been threatened by YouTube).

Please update it or make anonther project

### CODE REVIEW

**Comment by ndg63276** [comment]
Huh?

**Comment by filestoreinnet** [comment]
This function will really help to customise youtube, i hope you will create in future

**Comment by filestoreinnet** [comment]
http://randomstatus.in/others/youtube_search.php?q=love


https://www.googleapis.com/youtube/v3/search?part=id,snippet&type=video&maxResults=5&regionCode=IN&key=KEY


Both are responding same

So i wants to use my server at the place of youtube,
 This will avoide ip block buy youtube, as well as i can use multiple random developer key, +customise search results

So just give the option to use own server url for search page

**Comment by filestoreinnet** [comment]
And the same for youtube_dl

I have a server witch having youtube_dl and  generating video downloaing link as plain text
For example
http://randomstatus.in/others/youtube_search.php

So i dont want to use skill youtube_dl  i wants to use my server youtube_dl

**Comment by filestoreinnet** [comment]
Give a option like http://randomstatus.in/others/youtube_search.php?id=VIDEO_ID

Video id provided by skill

**Comment by filestoreinnet** [comment]
hello friend will you make this because i am facing too much api quota problem

**Comment by ndg63276** [comment]
Moving to issue #119

**Pull request closed without merging**
