### PR TITLE
Webserver

### PR DESCRIPTION
**Pull request by castrapel**
With some minor changes, I was able to get the service running locally on my raspberry pi instead of using a lambda function and figured this might be a good contribution. This is Python3.7 and intended to be installed in a virtualenv. Should also run fine on other OS's. I wanted to submit this PR before writing any docs to see if you would be willing to merge it.

### CODE REVIEW

**Comment by ndg63276** [comment]
Yeah seems like a really good idea. Can you make some documentation?

**Comment by ndg63276** [comment]
It would also be good to only have one copy of lambda_function.py in the repo, so any updates don't have to be committed twice. Could you use a symbolic link to point to the original?

**Comment by jamezrin** [comment]
I'm trying to do the same thing as this but with the python `http.server` instead of tornado, couldn't get it to work yet...

Is there any reason why there is a duplicated `lambda_function.py` file? @castrapel

**Comment by castrapel** [comment]
Sorry, I haven't had much time to work on this - It's a pet project with my kids, who love listening to Youtube audio on Alexa :-). If I recall correctly, I had to make some minor changes for Python 3.7 compatibility and to also use a proper virtual environment (Instead of statically-placed libraries which are required for Lambda deployment).

**Pull request closed without merging**
