### PR TITLE
Adding Brazilian Portuguese language

### PR DESCRIPTION
**Pull request by spyker0**

### CODE REVIEW

**Comment by ndg63276** [comment]
That's brilliant. Are you also able to translate some lines from strings.py? Can you add
```
strings_pt = {
'welcome1':"Bem-vindo ao Youtube. Digamos, por exemplo, reproduzir vídeos dos Beatles.",
...
}
```
etc?

**Comment by spyker0** [comment]
Sure, I'll do it!

**Comment by spyker0** [comment]
Done!

**Comment by ndg63276** [comment]
Thanks. I just need to add a line to lambda_function.py to use them.

**Pull request merged**
